---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-book-reprice-pad
  namespace: beta-app
  labels:
    app.kubernetes.io/name: hotel-book-reprice-pad
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hotel-book-reprice-pad
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hotel-book-reprice-pad
    spec:
      containers:
        - name: hotel-book-reprice-pad-api
          image: 306472407007.dkr.ecr.ap-south-1.amazonaws.com/ibs-skillset-happystays/hotel-book-reprice-pad:9d45e34
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8084
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          env:
            - name: HOST_CONFIG
              value: config-server
            - name: HOST_REGISTRY
              value: service-registry
