---
apiVersion: v1
kind: Service
metadata:
  name: hotel-book-reprice-pad
  namespace: beta-app
spec:
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app.kubernetes.io/name: hotel-book-reprice-pad